import { useAiCoach } from '../hooks/useAiCoach';
import type { AiCoachPayload } from '../hooks/useAiCoach';

export function AiCoachCard({ payload }: { payload: AiCoachPayload }) {
  const { state, text, error, ask, reset } = useAiCoach();

  return (
    <div className="card stack" aria-label="AI Coach">
      <div className="row-between">
        <div>
          <h2 style={{ margin: 0, fontSize: '1.15rem' }}>AI Coach note (optional)</h2>
          <p className="muted" style={{ margin: '2px 0 0' }}>
            A short, supplementary encouragement note generated by the local Copilot CLI. Your safe routine is already
            complete without it.
          </p>
        </div>
        <span className="tag tag--info">Optional · uses AI credits</span>
      </div>

      {state === 'idle' && (
        <div className="btn-row">
          <button className="btn btn--accent btn--sm" onClick={() => ask(payload)}>
            ✨ Ask the AI coach
          </button>
        </div>
      )}

      {state === 'loading' && (
        <p className="muted" role="status" aria-live="polite">
          Asking the AI coach… this can take a few seconds.
        </p>
      )}

      {state === 'done' && (
        <>
          <div className="exercise-reason" style={{ whiteSpace: 'pre-wrap' }} role="status">
            {text}
          </div>
          <div className="btn-row">
            <button className="btn btn--subtle btn--sm" onClick={() => ask(payload)}>
              Regenerate note
            </button>
            <button className="btn btn--ghost btn--sm" onClick={reset}>
              Dismiss
            </button>
          </div>
          <p className="muted" style={{ fontSize: '0.8rem', margin: 0 }}>
            AI-generated supplementary text. Not medical advice. Your routine’s safety is handled by the app’s
            deterministic engine, not the AI.
          </p>
        </>
      )}

      {state === 'offline' && (
        <div className="notice notice--info">
          <span className="ic" aria-hidden="true">ℹ️</span>
          <span>
            The optional AI coach server is not running, so we’ll skip it — everything else works normally. To enable
            it, run <code>npm run ai-server</code> in a terminal, then try again.
          </span>
        </div>
      )}

      {state === 'error' && (
        <div className="notice notice--info">
          <span className="ic" aria-hidden="true">ℹ️</span>
          <span>
            {error || 'The AI coach could not respond.'} You can continue without it, or try again.
            <br />
            <button className="btn btn--subtle btn--sm" style={{ marginTop: 8 }} onClick={() => ask(payload)}>
              Try again
            </button>
          </span>
        </div>
      )}
    </div>
  );
}
